export const orders = [
    {
      id: 1,
      img: "/1.jpg",
      customerName: "aaaaa",
      email: "...@gmail.com",
      phoneNumber: "white",
      customerAddress: "aaaaaaa",
      price: "$250.99",
      date: "01.02.2023",
      time: "12:12",
      riderName: "Amm",
      status: true,
    },
    {
        id: 2,
        img: "/2.jpg",
        customerName: "bbbbb",
        customerNumber: "white",
        customerAddress: "aaaaaaa",
        price: "$250.99",
        date: "01.02.2023",
        time: "12:12",
        riderName: "Amm",
        status: true,
      },
      {
        id: 3,
        img: "/3.jpg",
        customerName: "aaaaaaa",
        customerNumber: "white",
        customerAddress: "aaaaaaa",
        price: "$250.99",
        date: "01.02.2023",
        time: "12:12",
        riderName: "Amm",
        status: true,
      },
      {
        id: 4,
        img: "/4.jpg",
        customerName: "aaaaaaa",
        customerNumber: "white",
        customerAddress: "aaaaaaa",
        price: "$250.99",
        date: "01.02.2023",
        time: "12:12",
        riderName: "Amm",
        status: true,
      },
      {
        id: 5,
        img: "/5.jpg",
        customerName: "aaaaaaa",
        customerNumber: "white",
        customerAddress: "aaaaaaa",
        price: "$250.99",
        date: "01.02.2023",
        time: "12:12",
        riderName: "Amm",
        status: true,
      },
      {
        id: 6,
        img: "/6.jpg",
        customerName: "aaaaaaa",
        customerNumber: "white",
        customerAddress: "Saaaaaaa",
        price: "$250.99",
        date: "01.02.2023",
        time: "12:12",
        riderName: "Amm",
        status: true,
      },
      {
        id: 7,
        img: "/7.jpg",
        customerName: "Paaaaaaa",
        customerNumber: "white",
        customerAddress: "aaaaaaa",
        price: "$250.99",
        date: "01.02.2023",
        time: "12:12",
        riderName: "Amm",
        status: true,
      },
      {
        id: 8,
        img: "/8.jpg",
        customerName: "aaaaaaaion",
        customerNumber: "white",
        customerAddress: "Soaaaaaaa",
        price: "$250.99",
        date: "01.02.2023",
        time: "12:12",
        riderName: "Amm",
        status: true,
      },
      {
        id: 9,
        img: "/9.jpg",
        customerName: "aaaaaaa",
        customerNumber: "white",
        customerAddress: "Saaaaaaa",
        price: "$250.99",
        date: "01.02.2023",
        time: "12:12",
        riderName: "Amm",
        status: true,
      },
      {
        id: 10,
        img: "/10.jpg",
        customerName: "aaaaaaan",
        customerNumber: "white",
        customerAddress: "Saaaaaaa",
        price: "$250.99",
        date: "01.02.2023",
        time: "12:12",
        riderName: "Amm",
        delivered: true,
      },
    
  ];
  export const singleProduct = {
    id: 1,
    title: ": AAAAAAAA",
    img: "/1.jpg",
    info: {
      productId: ": 1",
      price: ": $250.99",
      Restraurent: ": Soo",
      CustomerName: ": Simolie",
      Address: ": 23rd road",
      MobileNo: ": 2222222",
    },
    id: 1,
    riderName: ": sssss",
    imgs: "https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=1600",
    infos: {
      Id: ": 1",
      price: ": $50.99",
      Location: ": 23rd road",
      MobileNo: ": 2222222",
    },
  };
export const riders =[
  {
    id: 1,
    img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    riderName: "Amm",
    email: "...@gmail.com",
    phoneNumber: "000000",
    status: true,
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=1600",
    riderName: "Amm",
    email: "...@gmail.com",
    phoneNumber: "000000",
    status: false,
  },
  {
    id: 3,
    img:  "https://images.pexels.com/photos/1587009/pexels-photo-1587009.jpeg?auto=compress&cs=tinysrgb&w=1600",
    riderName: "Amm",
    email: "...@gmail.com",
    phoneNumber: "000000",
    status: false,
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/871495/pexels-photo-871495.jpeg?auto=compress&cs=tinysrgb&w=1600",
    riderName: "Amm",
    email: "...@gmail.com",
    phoneNumber: "000000",
    status: true,
  },
  {
  id: 5,
    img: "https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=1600",
    riderName: "Amm",
    email: "...@gmail.com",
    phoneNumber: "000000",
    status: false,
  },
  {
    id: 6,
    img:  "https://images.pexels.com/photos/1587009/pexels-photo-1587009.jpeg?auto=compress&cs=tinysrgb&w=1600",
    riderName: "Amm",
    email: "...@gmail.com",
    phoneNumber: "000000",
    status: false,
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/871495/pexels-photo-871495.jpeg?auto=compress&cs=tinysrgb&w=1600",
    riderName: "Amm",
    email: "...@gmail.com",
    phoneNumber: "000000",
    status: true,
  },
  {
  id: 8,
    img: "https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=1600",
    riderName: "Amm",
    email: "...@gmail.com",
    phoneNumber: "000000",
    status: false,
  },
  {
    id: 9,
    img:  "https://images.pexels.com/photos/1587009/pexels-photo-1587009.jpeg?auto=compress&cs=tinysrgb&w=1600",
    riderName: "Amm",
    email: "...@gmail.com",
    phoneNumber: "000000",
    status: false,
  },
  {
    id: 10,
    img: "https://images.pexels.com/photos/871495/pexels-photo-871495.jpeg?auto=compress&cs=tinysrgb&w=1600",
    riderName: "Amm",
    email: "...@gmail.com",
    phoneNumber: "000000",
    status: true,
  },
];